; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "leveloid"
#define MyAppVersion "0.7"
#define MyAppPublisher "lainz"
#define MyAppURL "http://leveloid.sourceforge.net/"
#define MyAppExeName "leveloid.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A435B649-55FB-4E11-97F5-E4958EA02507}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commondocs}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename={#MyAppName} {#MyAppVersion}
Compression=lzma2/Ultra64
SolidCompression=true
InternalCompressLevel=Ultra64
ChangesAssociations=yes
SetupIconFile=leveloid.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
Name: "corsican"; MessagesFile: "compiler:Languages\Corsican.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "greek"; MessagesFile: "compiler:Languages\Greek.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "nepali"; MessagesFile: "compiler:Languages\Nepali.islu"
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "scottishgaelic"; MessagesFile: "compiler:Languages\ScottishGaelic.isl"
Name: "serbiancyrillic"; MessagesFile: "compiler:Languages\SerbianCyrillic.isl"
Name: "serbianlatin"; MessagesFile: "compiler:Languages\SerbianLatin.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "release\leveloid.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
; leveloid
Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloid"; ValueType: String; ValueData: "leveloid"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloid\DefaultIcon"; ValueType: String; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey
;Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloid\Shell\Open"; ValueName: Icon; ValueType: String; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloid\Shell\Open\Command"; ValueType: String; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey
;Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloid\Shell\Edit"; ValueName: Icon; ValueType: String; ValueData: "{app}\editor\editor.exe"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloid\Shell\Edit\Command"; ValueType: String; ValueData: """{app}\editor\editor.exe"" ""%1"""; Flags: uninsdeletekey

Root: HKLM; Subkey: "Software\Classes\.leveloid"; ValueType: String; ValueData: "leveloid.AssocFile.leveloid"; Flags: uninsdeletevalue uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\Classes\.leveloid"; ValueName: PerceivedType; ValueType: String; ValueData: "text"; Flags: uninsdeletevalue uninsdeletekeyifempty

; leveloidscript
Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloidscript"; ValueType: String; ValueData: "leveloid"; Flags: uninsdeletekey
;Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloidscript\Shell\Edit"; ValueName: Icon; ValueType: String; ValueData: "{app}\editor\editor.exe"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\leveloid.AssocFile.leveloidscript\Shell\Edit\Command"; ValueType: String; ValueData: """notepad.exe"" ""%1"""; Flags: uninsdeletekey

Root: HKLM; Subkey: "Software\Classes\.leveloidscript"; ValueType: String; ValueData: "leveloid.AssocFile.leveloidscript"; Flags: uninsdeletevalue uninsdeletekeyifempty
Root: HKLM; Subkey: "Software\Classes\.leveloidscript"; ValueName: PerceivedType; ValueType: String; ValueData: "text"; Flags: uninsdeletevalue uninsdeletekeyifempty

; default programs
Root: HKLM; Subkey: "Software\leveloid"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\leveloid\Capabilities"; ValueType: String; ValueName: "ApplicationName"; ValueData: {#MyAppName}; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\leveloid\Capabilities"; ValueType: String; ValueName: "ApplicationDescription"; ValueData: "http://leveloid.sourceforge.net/"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\leveloid\Capabilities\FileAssociations"; ValueName: ".leveloid"; ValueType: String; ValueData: "leveloid.AssocFile.leveloid"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\leveloid\Capabilities\FileAssociations"; ValueName: ".leveloidscript"; ValueType: String; ValueData: "leveloid.AssocFile.leveloidscript"; Flags: uninsdeletekey

Root: HKLM; Subkey: "Software\RegisteredApplications"; ValueType: String; ValueName: "leveloid"; ValueData: "Software\leveloid\Capabilities"; Flags: uninsdeletevalue uninsdeletekeyifempty
